version: '3'

services:
    mysql:
      container_name: mysql
      image: mysql:5.7
      restart: always
      volumes:
        - /var/lib/mysql
      ports:
        - 3306:3306
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: harvest_db
          MYSQL_USER: harvest_db
          MYSQL_PASSWORD: root

    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - 8080:80
      depends_on:
        - mysql
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: root

    backup_db:
      container_name: backup_db
      image: fradelg/mysql-cron-backup
      restart: always
      volumes:
        - ./db_backups:/backup
      depends_on:
        - mysql
      environment:
        MYSQL_HOST: mysql
        MYSQL_PORT: 3306
        MYSQL_DB:   harvest_db
        MYSQL_USER: harvest_db
        MYSQL_PASS: root
        CRON_TIME: '*/10 * * * *'
        MAX_BACKUPS: 10
        INIT_BACKUP: 'true'
